index_img: transparent
default_top_img: transparent
index_top_img_height: 480px
background: /img/top.jpg
footer_img: transparent
index_layout: 3

inject:
  head:
     - <link rel="stylesheet" href="/css/iconfont.css">
     - <link rel="stylesheet" href="/css/myStyle.css">
     #星空特效

  bottom:
    # - <script src="xxxx"></script>


nav:
  # Navigation bar logo image
  logo: /img/avater.jpg
  display_title: true
  # Whether to fix navigation bar
  fixed: false

code_blocks:
  # Code block theme: darker / pale night / light / ocean / false
  theme: ocean
  macStyle: false
  # Code block height limit (unit: px)
  height_limit: false
  word_wrap: false

  # Toolbar
  copy: true
  language: true
  # true: shrink the code blocks | false: expand the code blocks | none: expand code blocks and hide the button
  shrink: false
  fullpage: false


menu:
  主页: / || fas fa-home
  档案: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友情链接||fas fa-list:
    浪漫葱香的博客: https://romantoscalion.github.io/ || iconfont icon-chuyinweilai-daxiao
  #Link: /link/ || fas fa-link
 # About: /about/ || fas fa-heart

post_meta:
  # Home Page
  page:
    # Choose: created / updated / both
    date_type: created
    # Choose: date / relative
    date_format: date
    categories: true
    tags: true
    label: true
  post:
    # Choose: left / center
    position: left
    # Choose: created / updated / both
    date_type: both
    # Choose: date / relative
    date_format: date
    categories: true
    tags: true
    label: true


   
cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:


social:
   fas fa-brands fa-bilibili: https://space.bilibili.com/5712212 || Bilibili || '#4a7dbe'
   fas fa-solid fa-envelope: mailto:grasste0403@hotmail.com || E-mail || '#4a7dbe'

avatar:
  img: /img/avater.jpg
  effect: false

favicon: /img/avater.jpg

subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # Customize typed.js
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
  # source 調用第三方服務
  # false 關閉調用
  # 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # 2  調用一句網（簡體） http://yijuzhan.com/
  # 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: true
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 今天也是充满希望的一天
    - Have a nice day!


# Need to install the hexo-wordcount plugin
wordcount:
  enable: true
  # Display the word count of the article in post meta
  post_wordcount: true
  # Display the time to read the article in post meta
  min2read: true
  # Display the total word count of the website in aside's webinfo
  total_wordcount: true



blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
  font_family: 'Titillium Web'

